export enum ReduxWindowAction {
	TOGGLE_BRIEF_ABOUT_WINDOW = 'TOGGLE_BRIEF_WINDOW',
	TOGGLE_EXTENSIVE_ABOUT_WINDOW = 'TOGGLE_EXTENSIVE_ABOUT_WINDOW'
}

export enum ReduxStackCarouselAction {
    SET_ACTIVE_TAB_INDEX = 'SET_ACTIVE_TAB_INDEX'
}

export enum StackTab {
    BACKEND,
    FRONTEND,
    MOBILE
}
